### ISSUE TITLE
网上需要下载东西

### ISSUE THREAD

**Issue by pipijiev12** [nju-websoft/GenMC#1]
这个程序运行起来需要网上下载什么模型这么慢
![微信截图_20230110224903](https://user-images.githubusercontent.com/75164118/211582913-a31a0098-e533-4c81-97f6-5801834ae839.png)

**Comment by pipijiev12** [comment]
难道是t5的预训练模型？

**Comment by HuangZixian** [comment]
需要下载T5预训练模型，由参数 --model_path t5-base  配置。也可以配置为--model_path t5-small, 下载更轻量级的t5。
